language: objective-c
osx_image: xcode7.3

script:
  - cd MendeleyKit
  - pod install
  - xcodebuild -workspace MendeleyKit.xcworkspace -scheme MendeleyKitiOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test
  - xcodebuild -workspace MendeleyKit.xcworkspace -scheme MendeleyKitOSX test
